#cloud-config
hostname: omahouse-poc
users:
  - name: arch
    groups: [wheel]
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEjbc+HsfiufDqPuFK2pHeLWMq8gzmQ3jLsUjXzCTSWz vms-libvirt-descartaveis
ssh_pwauth: false
